### ISSUE TITLE
Demo of the url in automation 

### ISSUE THREAD

**Issue by dosipod** [ajotanc/PixelMagicTool#2]
There is no way to open discussion on your gh so we  just wanted to do small demo of how does it work  , browser has to be running for that to work 
![adj-url-pix-art4](https://github.com/ajotanc/wled-matrix-converter/assets/87589371/f738f742-0ea9-4e2e-9d9c-9eb000e0fab8)

**Comment by ajotanc** [comment]
> 

I didn't understand very well, in this case it's being a compliment or criticism about?
jsoskskaskks, I'm still learning English.

How do I stop releasing the discussion here on GH? I'm new to using it frequently, I'm still understanding how it works.

**Comment by dosipod** [comment]
Hey , i was just making a demo , no criticism  or complaint    you are doing good  @ajotanc

**Comment by ajotanc** [comment]
> Hey , i was just making a demo , no criticism or complaint you are doing good @ajotanc

Oh yes, thank you very much! 💙

**Comment by dosipod** [comment]
[loop_ajotanc.sh.txt](https://github.com/ajotanc/wled-matrix-converter/files/11637547/loop_ajotanc.sh.txt)
Yes it is working very well , i made a small script and it will take any file in the folder and display on matrix , very cool

**Comment by ajotanc** [comment]
> [loop_ajotanc.sh.txt](https://github.com/ajotanc/wled-matrix-converter/files/11637547/loop_ajotanc.sh.txt) Yes it is working very well , i made a small script and it will take any file in the folder and display on matrix , very cool . I will test the new changes you did

Remembering that it can be any type of image, jpeg, png, gif.
**This is very good, it left it well automated!**

**Comment by dosipod** [comment]
Yeah i changed the script now to take all files  , 
![image](https://github.com/ajotanc/wled-matrix-converter/assets/87589371/6ff6fcf3-575a-4da6-ad85-044f579856b1)
Only wokred correctly with pre_segment=individual else i see few strange pixels and some picts I got from the net are bad , i think there is specs for the pics to work better might be you know what will work better 

[loop_ajotanc.sh.txt](https://github.com/ajotanc/wled-matrix-converter/files/11644849/loop_ajotanc.sh.txt)

**Comment by ajotanc** [comment]
> Yeah i changed the script now to take all files , ![image](https://user-images.githubusercontent.com/87589371/243155688-6ff6fcf3-575a-4da6-ad85-044f579856b1.png) Only wokred correctly with pre_segment=individual else i see few strange pixels and some picts I got from the net are bad , i think there is specs for the pics to work better might be you know what will work better
> 
> [v2_ajotanc_loop.sh.txt](https://github.com/ajotanc/wled-matrix-converter/files/11644863/v2_ajotanc_loop.sh.txt)

The images need to be scalable, like jmsgens 16x16, 16x32 and so on, because when you grow it follows the .image pattern correctly. Regarding the pre_segment, for a 16x16 pixel it can be any one, but the main thing is individual, for others that are larger than 16x16 the ifeal is to use the range.

**Comment by dosipod** [comment]
I am trying what work best  , i got some that is 32 bit  and it looked really nice , still will look for more but this  two examples .

![agnes-and-unicorn-despicable-me](https://github.com/ajotanc/wled-matrix-converter/assets/87589371/ff4c577c-5f99-4dda-b3f6-95c985d1160e)
![anges](https://github.com/ajotanc/wled-matrix-converter/assets/87589371/aee1e635-4ce4-407e-a65b-e274036bb575)
![brown-skull-small](https://github.com/ajotanc/wled-matrix-converter/assets/87589371/0781469a-e986-4be4-94dc-7a3b83a8c721)
![skull](https://github.com/ajotanc/wled-matrix-converter/assets/87589371/e25f5529-14a2-4131-9e4f-363bfc89591d)
![image](https://github.com/ajotanc/wled-matrix-converter/assets/87589371/19c3dcd4-dfc4-48b8-bf0a-c8ce610b867c)

I can only edit  without losing transparency in paint 3d

**Comment by ajotanc** [comment]
> I am trying what work best , i got some that is 32 bit and it looked really nice , still will look for more but this two examples .
> 
> ![agnes-and-unicorn-despicable-me](https://user-images.githubusercontent.com/87589371/243205251-ff4c577c-5f99-4dda-b3f6-95c985d1160e.png) ![anges](https://user-images.githubusercontent.com/87589371/243205253-aee1e635-4ce4-407e-a65b-e274036bb575.jpg) ![brown-skull-small](https://user-images.githubusercontent.com/87589371/243205254-0781469a-e986-4be4-94dc-7a3b83a8c721.png) ![skull](https://user-images.githubusercontent.com/87589371/243205255-e25f5529-14a2-4131-9e4f-363bfc89591d.jpg) ![image](https://user-images.githubusercontent.com/87589371/243205266-19c3dcd4-dfc4-48b8-bf0a-c8ce610b867c.png)
> 
> I can only edit without losing transparency in paint 3d

In this case, the image does not have a transparent background, it only indicates that the image can be, but when it has these squares it does not mean that it is.. I will send you an example in which you will be able to change the background color.

![pngegg](https://github.com/ajotanc/wled-matrix-converter/assets/47322034/63c1484d-8126-4752-b42c-4476db02b5c7)
![Agnes](https://github.com/ajotanc/wled-matrix-converter/assets/47322034/c6beec9f-9813-4d4d-8bf0-c8ab6b4e9155)

When you want to look for images with a transparent background, search this way for "brown skull png" for example, or you can use Google's own tool to choose the output color you want.

![image](https://github.com/ajotanc/wled-matrix-converter/assets/47322034/27cee771-9f21-4356-b3df-4e30f9ad1055)

**Comment by dosipod** [comment]
I am trying to get a source folder  for images that can be directly integrated into your tool  ,  but i think that will be good idea for your app , also look at https://divoom.com/  they have a community in their app to share pics and gifs .  

One last thing , I think a lot of guys will start to use the tool now and i want  the url to be as short as possible , the Parameters names are too long , can you make it so  that for example output is replaced with ot and pre_segment to P_S ...etc  ,

**Comment by dosipod** [comment]
![June5_adj-url-pix16x32](https://github.com/ajotanc/wled-matrix-converter/assets/87589371/aebf3eb8-9cda-4a47-9c6b-af82da0ea453)

**Comment by dosipod** [comment]
I am trying to test the Transparent Image option but might be the images i tested do not work , can you send me an image that the option will work for if you could test . 
![image](https://github.com/ajotanc/wled-matrix-converter/assets/87589371/2056c220-e775-493d-a14c-1b7672ce9c50)

**Comment by ajotanc** [comment]
> 

It is in this sense the application itself! About shortening the parameters, yes, but I need to see what I need to do to change.

**Comment by ajotanc** [comment]
> I am trying to test the Transparent Image option but might be the images i tested do not work , can you send me an image that the option will work for if you could test . ![image](https://user-images.githubusercontent.com/87589371/243353025-2056c220-e775-493d-a14c-1b7672ce9c50.png)

Use the 200w.gif image it has a transparent background, in this case this option is only valid for images that do not have a background (transparent background)

**Comment by ajotanc** [comment]
@dosipod The parameters can already be used shortened, please take a look at the readme.

**Comment by dosipod** [comment]
Transparent Image change color works now 👍 

![image](https://github.com/ajotanc/PixelMagicTool/assets/87589371/3b3d204c-adb9-454c-b78e-c57a03a76847)

**Comment by dosipod** [comment]
Shortened  parameters  works fire 👍 

curl -s -F "file=@$file" "https://ajota.vercel.app/api/wled/image?id=0&o=curl&bri=7&ps=individual&w=32&h=16&hn=10.0.6.70&c=3CCFFE5" >tmp01.sh
